require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RefugioApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'EscPos', :path => '../node_modules/@leesiongchan/react-native-esc-pos'

  target 'RefugioAppTests' do
    inherit! :complete
    # Pods for testing
  end


end

target 'RefugioApp-tvOS' do
  # Pods for RefugioApp-tvOS

  target 'RefugioApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
